blocked = "bot was blocked by the user"
start = "Hello! This is your start message!"
ban = "you were banned by the admin!"
unban = "you were unbanned by the admin."
text_message = "Message that would be send if somebody writes any text"
banned = "you are blocked"
main_id = 1111 #id without quotes #can be group id
TOKEN = "1297441208:##############"
notallowed = "Не перессылайте мне сообщение!"